# Generated by Django 4.2.7 on 2023-11-16 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meus_livros",
            old_name="pago",
            new_name="lido",
        ),
    ]
