# Generated by Django 4.2.7 on 2023-11-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0002_rename_pago_meus_livros_lido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meus_livros",
            name="valor",
        ),
        migrations.AddField(
            model_name="meus_livros",
            name="resumo",
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
