# Generated by Django 4.2.7 on 2023-11-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0003_remove_meus_livros_valor_meus_livros_resumo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meus_livros",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
    ]
