# Generated by Django 4.2.7 on 2023-11-18 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0004_alter_meus_livros_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meus_livros",
            old_name="data",
            new_name="data_termino",
        ),
        migrations.AddField(
            model_name="meus_livros",
            name="data_inicio",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
